### ISSUE TITLE
Strange stack traces

### ISSUE THREAD

**Issue by apkh** [apkh/ez#2]
Strange stack traces appear all time during client or test execution:

DEBUG [Grizzly(1)](RexProClientFilter.java:99) - Received message [version:1][message type:5][body length:40][body:-107 -80  0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    -80  -87  73   93   111  102  -1   71   -113 -110 60   113  -14  43   -101 -121 9    -128 -110 36   52   -128]
DEBUG [Grizzly(2)](RexProClientFilter.java:99) - Received message [version:1][message type:5][body length:38][body:-107 -80  0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    -80  30   -103 -72  96   48   40   78   77   -114 72   54   -59  -74  -56  -46  42   -128 -112 -128]
Jan 04, 2014 3:33:26 PM org.glassfish.grizzly.nio.transport.TCPNIOTransport configureChannel
WARNING: Can not set keepAlive to false
java.net.SocketException: Invalid argument: no further information
    at sun.nio.ch.Net.setIntOption0(Native Method)
    at sun.nio.ch.Net.setSocketOption(Net.java:373)
    at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:189)
    at sun.nio.ch.SocketAdaptor.setBooleanOption(SocketAdaptor.java:295)
    at sun.nio.ch.SocketAdaptor.setKeepAlive(SocketAdaptor.java:397)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.configureChannel(TCPNIOTransport.java:639)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler.onConnectedAsync(TCPNIOConnectorHandler.java:213)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler$1.completed(TCPNIOConnectorHandler.java:154)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler$1.completed(TCPNIOConnectorHandler.java:150)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnection.onConnect(TCPNIOConnection.java:210)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:804)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy.executeIoEvent(LeaderFollowerNIOStrategy.java:106)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:88)
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:398)
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:368)
    at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:334)
    at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:264)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:567)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:547)
    at java.lang.Thread.run(Thread.java:724)

Jan 04, 2014 3:33:26 PM org.glassfish.grizzly.nio.transport.TCPNIOTransport configureChannel
WARNING: Can not set TcpNoDelay to true
java.net.SocketException: Invalid argument: no further information
    at sun.nio.ch.Net.setIntOption0(Native Method)
    at sun.nio.ch.Net.setSocketOption(Net.java:373)
    at sun.nio.ch.SocketChannelImpl.setOption(SocketChannelImpl.java:189)
    at sun.nio.ch.SocketAdaptor.setBooleanOption(SocketAdaptor.java:295)
    at sun.nio.ch.SocketAdaptor.setTcpNoDelay(SocketAdaptor.java:330)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.configureChannel(TCPNIOTransport.java:645)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler.onConnectedAsync(TCPNIOConnectorHandler.java:213)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler$1.completed(TCPNIOConnectorHandler.java:154)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler$1.completed(TCPNIOConnectorHandler.java:150)
    at org.glassfish.grizzly.nio.transport.TCPNIOConnection.onConnect(TCPNIOConnection.java:210)
    at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:804)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:112)
    at org.glassfish.grizzly.strategies.LeaderFollowerNIOStrategy.executeIoEvent(LeaderFollowerNIOStrategy.java:106)
    at org.glassfish.grizzly.strategies.AbstractIOStrategy.executeIoEvent(AbstractIOStrategy.java:88)
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeyEvents(SelectorRunner.java:398)
    at org.glassfish.grizzly.nio.SelectorRunner.iterateKeys(SelectorRunner.java:368)
    at org.glassfish.grizzly.nio.SelectorRunner.doSelect(SelectorRunner.java:334)
    at org.glassfish.grizzly.nio.SelectorRunner.run(SelectorRunner.java:264)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:567)
    at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:547)
    at java.lang.Thread.run(Thread.java:724)

DEBUG [Grizzly(1)](RexProClientFilter.java:99) - Received message [version:1][message type:5][body length:44][body:-107 -80  0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    0    -80  -89  -38  98   -46  49   -69  76   24   -128 9    -58  5    34   24   -53  -86  -128 -111 -91  65   68   77   73   78   -128]

**Comment by nickvl** [comment]
https://github.com/inthefabric/RexConnect/issues/7

**Comment by apkh** [comment]
I asume both issues can be tied with not closed connections
