### ISSUE TITLE
Node removal doesn't work

### ISSUE THREAD

**Issue by apkh** [apkh/ez#44]
DEBUG [EZapp commands dispatcher] [id_49:ServerFacadeImpl] - returning: deleteNode(2 arguments):void
ERROR [pool-2-thread-1] [id_49:InMemoryMessageRelay] - Response msg was not delivered to the client
java.lang.UnsupportedOperationException
    at java.util.AbstractMap.put(AbstractMap.java:203)
    at ru.ezdz.context.service.messaging.CallbackService$MessageListener.getPayload(CallbackService.java:81)
    at ru.ezdz.context.service.messaging.CallbackService$MessageListener.onMessage(CallbackService.java:50)
    at ru.ezdz.context.service.graph.impl.InMemoryMessageRelay$1.run(InMemoryMessageRelay.java:96)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)

**Comment by nickvl** [comment]
fixed. inappropriate using unmodifiable map
